listsite/listexpress/urls.py
from django.conf.urls import url

from . import views

app_name = 'listexpress'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # ex: /list/5/
    url(r'^list/(?P<itemlist_id>[0-9]+)/$', views.listdetail, name='listdetail'),
    # ex: /list/5/buildcomparisons
    url(r'^list/(?P<itemlist_id>[0-9]+)/buildcomparisons/$', views.buildcomparisons, name='buildcomparisons'),
    # ex: /list/5/comparisonvote
    url(r'^list/(?P<itemlist_id>[0-9]+)/comparisonvote/$', views.comparisonvote, name='comparisonvote'),
    # ex: /list/5/comparisonvote with votedComparison_id and vote specified
    url(r'^list/(?P<itemlist_id>[0-9]+)/comparisonvote/(?P<votedComparison_id>[0-9]+)/(?P<vote>[0-9]?)/$', views.comparisonvote, name='comparisonvote'),
    # ex: /list/5/buildcomparisons
    url(r'^list/(?P<itemlist_id>[0-9]+)/orderlist/$', views.orderlist, name='orderlist'),
]

listsite/listsite/urls.py
from django.conf.urls import include, url
import django.contrib.auth.views

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'', include('listexpress.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('vote.urls')),
]

listsite/listexpress/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Member(models.Model):
    created_date = models.DateTimeField(default=timezone.now)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class ItemList(models.Model):
    created_date = models.DateTimeField(default=timezone.now)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    list_name = models.CharField(max_length=200, default='UNNAMED LIST')
    num_items = models.IntegerField(default=None, blank=True, null=True)
    num_comparisons = models.IntegerField(default=None, blank=True, null=True)
    fully_defined = models.BooleanField(default=False)

    def __str__(self):
        return self.list_name

class Item(models.Model):
    created_date = models.DateTimeField(default=timezone.now)
    itemlist = models.ForeignKey(ItemList, on_delete=models.CASCADE)
    item_name = models.CharField(max_length=100, default='UNNAMED ITEM')
    order_index = models.IntegerField(default=0)

    def __str__(self):
        return self.item_name

class ItemComparison(models.Model):
    created_date = models.DateTimeField(default=timezone.now)
    itemlist = models.ForeignKey(ItemList, on_delete=models.CASCADE)
    item1_index = models.IntegerField(default=0)
    item2_index = models.IntegerField(default=0)
    comparison_name = models.CharField(max_length=205, default='UNNAMED COMPARISON')
    true_votes = models.IntegerField(default=0)
    false_votes = models.IntegerField(default=0)

    def __str__(self):
        return self.comparison_name

listsite/listexpress/views.py
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import get_object_or_404, get_list_or_404, render
from .models import ItemList, Item, ItemComparison
from .Concept import *
from django.contrib.auth.decorators import login_required
import random

def index(request):
    context = {}

    #Gets the User information
    user = None
    if request.user.is_authenticated():
        user = request.user

    #Gets information on existing ItemLists
    itemlists = ItemList.objects.all()
    context['itemlists'] = itemlists

    #If the user is logged in, we include their lists separately
    user_itemlists = []
    if user:
        user_itemlists = user.member.itemlist_set.all()
    context['user_itemlists'] = user_itemlists
    context['user'] = user

    return render(request, 'listexpress/index.html', context)

def listdetail(request, itemlist_id):
    context = {}

    #Gets the User information
    user = None
    if request.user.is_authenticated():
        user = request.user

    #Gets the ItemList and Item information
    itemlist = get_object_or_404(ItemList, pk=itemlist_id)
    items = itemlist.item_set.order_by('order_index', 'id')
    context['itemlist'] = itemlist
    context['items'] = items
    if itemlist.fully_defined:
        comparisons = itemlist.itemcomparison_set.all()
        context['comparisons'] = comparisons

        #Checks if each comparison has been voted on at least numItems times
        #Note: numItems may not be a good threshold as list size increases but I'm not sure.
        #For this reason, I'm keeping track of total votes as well.
        canOrder = True
        numItems = itemlist.num_items
        totalVotes = 0
        for comparison in comparisons:
            comparisonVotes = comparison.true_votes + comparison.false_votes
            if ((canOrder) and (comparisonVotes < numItems)):
                canOrder = False
            totalVotes += comparisonVotes

    #Determines if the ItemList was created by the User
    userOwnsList = False
    if user:
        if user == itemlist.member.user:
            userOwnsList = True
    context['userOwnsList'] = userOwnsList

    return render(request, 'listexpress/listdetail.html', context)

@login_required
def orderlist(request, itemlist_id):
    context = {}

    #Gets the ItemList information
    itemlist = get_object_or_404(ItemList, pk=itemlist_id)

    #Ensure that the user calling this view is the owner of the list
    user = request.user
    creator = itemlist.member.user
    if user != creator:
        return HttpResponseForbidden('<h1>You are not authorized to request the ordering of a list which you did not create</h1>')
    elif not itemlist.fully_defined:
        return HttpResponseForbidden('<h1>A list cannot be ordered before comparisons are built</h1>')
    else:
        userOwnsList = True

        #Gets lists of ItemComparison objects, and of Item objects, from the ItemList.
        #NOTE: Down the line, I should rename anything in Concept.py which implies that the file is simply a test
        items = itemlist.item_set.all()
        comparisons = itemlist.itemcomparison_set.all()

        #Initializes the Test object and sets the appropriate numElts value
        test = Test()
        test.setNumElts(len(items))

        #Populates test with data from the ItemComparison objects
        for i, itemComparison in enumerate(comparisons):

            #NOTE: This might be backwards (switch the vote order if the list is ordered backwards)
            test.addComparison(Comparison(itemComparison.true_votes, itemComparison.false_votes, i))

        #Gets the resultant Hasse list from test
        hasse = processTest(test)

        #Reassigns the order_index values for each Item in items, according to hasse.
        for i, hasseVal in enumerate(hasse):
            items[hasseVal].order_index = i

        #Saves each Item
        for item in items:
            item.save()

        #Populates context.
        #(NOTE:) This is done in the same fashion as listdetail() because the same information is known
        context['itemlist'] = itemlist
        context['items'] = items
        context['comparisons'] = comparisons
        context['userOwnsList'] = userOwnsList

        return render(request, 'listexpress/listdetail.html', context)

def comparisonvote(request, itemlist_id, votedComparison_id=None, vote=None):
    context = {}

    #Votes on the old content, if applicable
    if not (votedComparison_id is None):
        if not (vote is None):
            votedComparison = get_object_or_404(ItemComparison, pk=votedComparison_id)

            #If the user voted that item1 > item2
            if vote == '1':
                votedComparison.true_votes += 1
                votedComparison.save()

            #If the user voted that item2 > item1
            elif vote == '2':
                votedComparison.false_votes += 1
                votedComparison.save()

            #If vote is not '1' or '2'
            else:
                print(vote)
                return HttpResponseForbidden('<h1>vote must be a string equal to either \'1\' or \'2\'</h1>')
        else:
            return HttpResponseForbidden('<h1>A comparison_id was provided, but vote=None</h1>')

    #Generates the new content to be voted on
    #Gets the ItemList, ItemComparison and Item information
    itemlist = get_object_or_404(ItemList, pk=itemlist_id)
    comparisonIndex = random.randrange(itemlist.num_comparisons)
    itemcomparison = itemlist.itemcomparison_set.all()[comparisonIndex]
    items = itemlist.item_set.all()
    item1 = items[itemcomparison.item1_index]
    item2 = items[itemcomparison.item2_index]
    context['itemlist'] = itemlist
    context['itemcomparison'] = itemcomparison
    context['item1'] = item1
    context['item2'] = item2

    return render(request, 'listexpress/comparisonvote.html', context)

@login_required
def buildcomparisons(request, itemlist_id):
    context = {}

    #Gets the ItemList information
    itemlist = get_object_or_404(ItemList, pk=itemlist_id)

    #Ensure that the user calling this view is the owner of the list
    user = request.user
    creator = itemlist.member.user
    if user != creator:
        return HttpResponseForbidden('<h1>You are not authorized to build comparisons for a list which you did not create</h1>')
    else:
        itemlist = get_object_or_404(ItemList, pk=itemlist_id)
        items = itemlist.item_set.all()
        numItems = items.count()
        numComparisons = itemlist.itemcomparison_set.count()
        itemlist.fully_defined = ((numComparisons) == ((numItems * numItems - numItems) / 2))
        #If the comparisons have not been built yet or were built incorrectly
        if not itemlist.fully_defined:
            for i in range(numItems - 1):
                for j in range(i + 1, numItems):
                    itemlist.itemcomparison_set.create(item1_index=i,
                                                       item2_index=j,
                                                       comparison_name=(items[i].item_name +
                                                                        " vs. " +
                                                                        items[j].item_name))
            itemlist.num_items = numItems
            numComparisons = itemlist.itemcomparison_set.count()
            itemlist.num_comparisons = numComparisons
            itemlist.fully_defined = True
            itemlist.save()
            itemcomparisons = itemlist.itemcomparison_set.all()
            context['itemlist'] = itemlist
            context['itemcomparisons'] = itemcomparisons
            return render(request, 'listexpress/buildcomparisons.html', context)

        #If the comparisons have already been built
        else:
            return HttpResponseForbidden('<h1>You are not authorized to rebuild comparisons for this list</h1>')

listsite/listexpress/templates/listexpress/base.html
{% load staticfiles %}
<html>
    <head>
        <title>ListExpress</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <p>You are currently logged in!</p>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1><a href="/">ListExpress</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

listsite/listexpress/templates/listexpress/buildcomparisons.html
{% extends 'listexpress/base.html' %}

{% block content %}
    <h1>List: {{ itemlist.list_name }}</h1>
    <p><a href="{% url 'listexpress:listdetail' itemlist.id %}">Return to your list: {{ itemlist.list_name }}</a></p>
    <h3>Successfuly built comparisons:</h3>
    <ul>
        {% for itemcomparison in itemcomparisons %}
            <li>{{ itemcomparison.comparison_name }}</li>
        {% endfor %}
    </ul>
    <p><a href="{% url 'listexpress:listdetail' itemlist.id %}">Return to your list: {{ itemlist.list_name }}</a></p>
{% endblock %}

listsite/listexpress/templates/listexpress/comparisonvote.html
{% extends 'listexpress/base.html' %}

{% block content %}
    <h1>Voting on list: {{ itemlist.list_name }}</h1>
    <h3>Comparison: {{ itemcomparison.comparison_name }}</h3>
    <h1><a href="{% url 'listexpress:comparisonvote' itemlist.id itemcomparison.id 1 %}">{{ item1.item_name }} is better!</a></h1>
    <h1><a href="{% url 'listexpress:comparisonvote' itemlist.id itemcomparison.id 2 %}">{{ item2.item_name }} is better!</a></h1>
    <h1><a href="{% url 'listexpress:comparisonvote' itemlist.id %}">I don't care.</a></h1>
    
    <p><a href="{% url 'listexpress:listdetail' itemlist.id %}">Return to list: {{ itemlist.list_name }}</a></p>
{% endblock %}

listsite/listexpress/templates/listexpress/index.html
{% extends 'listexpress/base.html' %}

{% block content %}
    {% if itemlists %}
        <h3>Lists:</h3>
        {% for itemlist in itemlists %}
            <li><a href="{% url 'listexpress:listdetail' itemlist.id %}">{{ itemlist.list_name }}</a></li>
        {% endfor %}
    {% else %}
        <h3>No ItemList objects exist yet.</h3>
    {% endif %}
    
    {% if user %}
        {% if user_itemlists %}
            <h3>Your lists:</h3>
            {% for user_itemlist in user_itemlists %}
                <li><a href="{% url 'listexpress:listdetail' user_itemlist.id %}">{{ user_itemlist.list_name }}</a></li>
            {% endfor %}
        {% else %}
            <h3>You haven't made any lists yet.</h3>
        {% endif %}
    {% endif %}
    
{% endblock %}

listsite/listexpress/templates/listexpress/listdetail.html
{% extends 'listexpress/base.html' %}

{% block content %}
    <h1>List: {{ itemlist.list_name }}</h1>
    
    {% if itemlist.fully_defined %}
        <h1><a href="{% url 'listexpress:comparisonvote' itemlist.id %}">Vote!</a></h1>
    {% else %}
        {% if userOwnsList %}
            <h3>People will be able to vote once you build comparisons for this list.</h3>
        {% else %}
            <h3>You will be able to vote once the list creator finalizes this list.</h3>
        {% endif %}
    {% endif %}
    
    <h3>Items</h3>
    {% if userOwnsList and itemlist.fully_defined %}
        <p>You created this list! <a href="{% url 'listexpress:orderlist' itemlist.id %}">Want to order it based on current vote data?</a></p>
    {% endif %}
    {% for item in items %}
        <li>{{ item.item_name }}</li>
    {% endfor %}
    
    
    {% if itemlist.fully_defined %}
        <h3>Comparisons</h3>
        <table class = "table">
            <thead>
                <th>Comparison</th>
                <th>Votes for 1</th>
                <th>Votes for 2</th>
            </thead>
            <tbody>
                {% for comparison in comparisons %}
                    <tr>
                        <td>{{ comparison.comparison_name }}</td>
                        {% if userOwnsList %}
                            <td>{{ comparison.true_votes }}</td>
                            <td>{{ comparison.false_votes }}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h3>Comparisons have not yet been built.</h3>
        {% if userOwnsList %}
            <p>You created this list! <a href="{% url 'listexpress:buildcomparisons' itemlist.id %}">Want to build comparisons now?</a></p>
        {% endif %}
    {% endif %}
{% endblock %}